config/routes.rb
Rails.application.routes.draw do
  resources :users
  get :assign_roles, to: 'users#assign_roles'
  put "user/:id/assign_roles", to: 'users#update'
  root 'users#assign_roles'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.all
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      redirect_to :back
    end
  end

  def edit
  end

  def update
    user = User.find(params[:id])
    puts params.fetch(:role)
    user.update_attributes(role: params.fetch(:role))
    puts "user role updated"
    #respond_to do |format|
    #  if @user.save
    #    format.html { redirect_to 'users/index' }
    #    format.js   {}
    #    format.json {}
    #  end
    #end
  end

  def assign_roles
    @users = User.all
    @roles = ["", "milk drinker", "cookie dipper", "cookie counter"]

  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:id, :name, :role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ajaxrails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/assign_roles.html.erb
<%= link_to "All Users", users_path %>
<% @users.each do |u| %>
  <ul>
    <li><%= u.name %>
        <%= form_for u, remote: true do |f| %>
          <%= f.label :role %>
          <%= f.select :role, options_for_select(@roles, u.role), {}, {class: "role", id: "#{u.id}"} %>
        <% end %>
    </li>
  </ul>
<% end %>

app/views/users/index.html.erb
<%= link_to "Assign Roles", assign_roles_path %>
<%= link_to "New User", new_user_path %>
<h1>All Users<h2>
<% @users.each do |u| %>
  <div><%= link_to u.name, user_path(u) %>, <%= u.role %></div>
<% end %>

app/views/users/new.html.erb
<% flash.each do |f, msg| %>
  <%= msg %>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.hidden_field(:role, value: "") %>

  <%= f.submit "Create User" %>
<% end %>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.role %>